In [81]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"D:\data_mining\tuan5\data.csv")
print(df)

    TID                                  Itemset
0     1  Wine, Chips, Bread, Butter, Milk, Apple
1     2                Wine, Bread, Butter, Milk
2     3                      Bread, Butter, Milk
3     4                             Chips, Apple
4     5  Wine, Chips, Bread, Butter, Milk, Apple
5     6                        Wine, Chips, Milk
6     7        Wine, Chips, Bread, Butter, Apple
7     8                        Wine, Chips, Milk
8     9                       Wine, Bread, Apple
9    10                Wine, Bread, Butter, Milk
10   11              Chips, Bread, Butter, Apple
11   12                Wine, Butter, Milk, Apple
12   13         Wine, Chips, Bread, Butter, Milk
13   14                 Wine, Bread, Milk, Apple
14   15         Wine, Bread, Butter, Milk, Apple
15   16  Wine, Chips, Bread, Butter, Milk, Apple
16   17        Chips, Bread, Butter, Milk, Apple
17   18               Chips, Butter, Milk, Apple
18   19  Wine, Chips, Bread, Butter, Milk, Apple
19   20         Wine, Bread, Butter, Milk, Apple
20   21          Wine, Chips, Bread, Milk, Apple
21   22                                    Chips

In [82]:
df['Itemset'] = df['Itemset'].str.split(r',\s*')
df_exploded = df.explode('Itemset')
df1 = (
    df_exploded.groupby('Itemset')['TID']
    .apply(lambda x: ', '.join(x.astype(str)))
    .reset_index()
)
df1.columns = ['Items', 'TID list']

print(df1)

    Items                                           TID list
0   Apple  1, 4, 5, 7, 9, 11, 12, 14, 15, 16, 17, 18, 19,...
1   Bread  1, 2, 3, 5, 7, 9, 10, 11, 13, 14, 15, 16, 17, ...
2  Butter  1, 2, 3, 5, 7, 10, 11, 12, 13, 15, 16, 17, 18,...
3   Chips   1, 4, 5, 6, 7, 8, 11, 13, 16, 17, 18, 19, 21, 22
4    Milk  1, 2, 3, 5, 6, 8, 10, 12, 13, 14, 15, 16, 17, ...
5    Wine  1, 2, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 1...

In [83]:
min_support = 0.5
min_combination = 2

In [92]:
df1['Count'] = df1['TID list'].str.count(',') + 1
df1['Support'] = df1['Count'] / 22

df1 = df1[df1['Count'] >= min_combination]
df1 = df1[df1['Support'] >= min_support]
df1

    Items                                           TID list  Count   Support
0   Apple  1, 4, 5, 7, 9, 11, 12, 14, 15, 16, 17, 18, 19,...     15  0.681818
1   Bread  1, 2, 3, 5, 7, 9, 10, 11, 13, 14, 15, 16, 17, ...     16  0.727273
2  Butter  1, 2, 3, 5, 7, 10, 11, 12, 13, 15, 16, 17, 18,...     15  0.681818
3   Chips   1, 4, 5, 6, 7, 8, 11, 13, 16, 17, 18, 19, 21, 22     14  0.636364
4    Milk  1, 2, 3, 5, 6, 8, 10, 12, 13, 14, 15, 16, 17, ...     17  0.772727
5    Wine  1, 2, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 1...     16  0.727273

In [91]:
F2 = []
for i in range(df1.shape[0]):
    for j in range(i + 1, df1.shape[0]):
        # .split(', ') để tách thành list, sau đó set() để chuyển thành tập hợp
        set_i = set(df1.iloc[i]['TID list'].split(', '))
        set_j = set(df1.iloc[j]['TID list'].split(', '))
        
        # TÌM GIAO NHAU (Các TID xuất hiện ở cả 2 hàng)
        common_tids = set_i.intersection(set_j)
        
        # ĐỊNH DẠNG LẠI KẾT QUẢ
        if common_tids:
            tid_str = ', '.join(sorted(list(common_tids), key=int))
        else:
            tid_str = '-'

        F2.append([df1.iloc[i, 0] + ", " + df1.iloc[j, 0], tid_str])

df2 = pd.DataFrame(F2, columns=['Items', 'TID list'])
df2

            Items                                           TID list
0    Apple, Bread         1, 5, 7, 9, 11, 14, 15, 16, 17, 19, 20, 21
1   Apple, Butter            1, 5, 7, 11, 12, 15, 16, 17, 18, 19, 20
2    Apple, Chips                 1, 4, 5, 7, 11, 16, 17, 18, 19, 21
3     Apple, Milk           1, 5, 12, 14, 15, 16, 17, 18, 19, 20, 21
4     Apple, Wine             1, 5, 7, 9, 12, 14, 15, 16, 19, 20, 21
5   Bread, Butter      1, 2, 3, 5, 7, 10, 11, 13, 15, 16, 17, 19, 20
6    Bread, Chips                    1, 5, 7, 11, 13, 16, 17, 19, 21
7     Bread, Milk     1, 2, 3, 5, 10, 13, 14, 15, 16, 17, 19, 20, 21
8     Bread, Wine      1, 2, 5, 7, 9, 10, 13, 14, 15, 16, 19, 20, 21
9   Butter, Chips                    1, 5, 7, 11, 13, 16, 17, 18, 19
10   Butter, Milk     1, 2, 3, 5, 10, 12, 13, 15, 16, 17, 18, 19, 20
11   Butter, Wine             1, 2, 5, 7, 10, 12, 13, 15, 16, 19, 20
12    Chips, Milk                 1, 5, 6, 8, 13, 16, 17, 18, 19, 21
13    Chips, Wine                      1, 5, 6, 7, 8, 13, 16, 19, 21
14     Milk, Wine  1, 2, 5, 6, 8, 10, 12, 13, 14, 15, 16, 19, 20, 21

In [93]:
df2['Count'] = df2['TID list'].str.count(',') + 1
df2['Support'] = df2['Count'] / 22

df2 = df2[df2['Count'] >= min_combination]
df2 = df2[df2['Support'] >= min_support]
df2

,Items,TID list,Count,Support
0,"Apple, Bread","1, 5, 7, 9, 11, 14, 15, 16, 17, 19, 20, 21",12,0.545455
1,"Apple, Butter","1, 5, 7, 11, 12, 15, 16, 17, 18, 19, 20",11,0.500000
3,"Apple, Milk","1, 5, 12, 14, 15, 16, 17, 18, 19, 20, 21",11,0.500000
4,"Apple, Wine","1, 5, 7, 9, 12, 14, 15, 16, 19, 20, 21",11,0.500000
5,"Bread, Butter","1, 2, 3, 5, 7, 10, 11, 13, 15, 16, 17, 19, 20",13,0.590909
7,"Bread, Milk","1, 2, 3, 5, 10, 13, 14, 15, 16, 17, 19, 20, 21",13,0.590909
8,"Bread, Wine","1, 2, 5, 7, 9, 10, 13, 14, 15, 16, 19, 20, 21",13,0.590909
10,"Butter, Milk","1, 2, 3, 5, 10, 12, 13, 15, 16, 17, 18, 19, 20",13,0.590909
11,"Butter, Wine","1, 2, 5, 7, 10, 12, 13, 15, 16, 19, 20",11,0.500000
14,"Milk, Wine","1, 2, 5, 6, 8, 10, 12, 13, 14, 15, 16, 19, 20, 21",14,0.636364

In [78]:
F3 = []
for i in range(df1.shape[0]):
    for j in range(i + 1, df1.shape[0]):
        for k in range(j + 1, df1.shape[0]):
            # .split(', ') để tách thành list, sau đó set() để chuyển thành tập hợp
            set_i = set(df1.iloc[i]['TID list'].split(', '))
            set_j = set(df1.iloc[j]['TID list'].split(', '))
            set_k = set(df1.iloc[k]['TID list'].split(', '))
            
            # TÌM GIAO NHAU (Các TID xuất hiện ở cả 3 hàng)
            common_tids = set_i.intersection(set_j, set_k)
            
            # ĐỊNH DẠNG LẠI KẾT QUẢ
            if common_tids:
                tid_str = ', '.join(sorted(list(common_tids), key=int))
            else:
                tid_str = '-'

            F3.append([df1.iloc[i, 0] + ", " + df1.iloc[j, 0] + ", " + df1.iloc[k , 0], 
                       tid_str])

df3 = pd.DataFrame(F3, columns=['Items', 'TID list'])
df3

                   Items                                 TID list
0   Apple, Bread, Butter          1, 5, 7, 11, 15, 16, 17, 19, 20
1    Apple, Bread, Chips              1, 5, 7, 11, 16, 17, 19, 21
2     Apple, Bread, Milk         1, 5, 14, 15, 16, 17, 19, 20, 21
3     Apple, Bread, Wine       1, 5, 7, 9, 14, 15, 16, 19, 20, 21
4   Apple, Butter, Chips              1, 5, 7, 11, 16, 17, 18, 19
5    Apple, Butter, Milk         1, 5, 12, 15, 16, 17, 18, 19, 20
6    Apple, Butter, Wine              1, 5, 7, 12, 15, 16, 19, 20
7     Apple, Chips, Milk                 1, 5, 16, 17, 18, 19, 21
8     Apple, Chips, Wine                      1, 5, 7, 16, 19, 21
9      Apple, Milk, Wine         1, 5, 12, 14, 15, 16, 19, 20, 21
10  Bread, Butter, Chips              1, 5, 7, 11, 13, 16, 17, 19
11   Bread, Butter, Milk   1, 2, 3, 5, 10, 13, 15, 16, 17, 19, 20
12   Bread, Butter, Wine       1, 2, 5, 7, 10, 13, 15, 16, 19, 20
13    Bread, Chips, Milk                 1, 5, 13, 16, 17, 19, 21
14    Bread, Chips, Wine                  1, 5, 7, 13, 16, 19, 21
15     Bread, Milk, Wine  1, 2, 5, 10, 13, 14, 15, 16, 19, 20, 21
16   Butter, Chips, Milk                 1, 5, 13, 16, 17, 18, 19
17   Butter, Chips, Wine                      1, 5, 7, 13, 16, 19
18    Butter, Milk, Wine      1, 2, 5, 10, 12, 13, 15, 16, 19, 20
19     Chips, Milk, Wine               1, 5, 6, 8, 13, 16, 19, 21

In [94]:
df3['Count'] = df3['TID list'].str.count(',') + 1
df3['Support'] = df3['Count'] / 22

df3 = df3[df3['Count'] >= min_combination]
df3 = df3[df3['Support'] >= min_support]
df3

,Items,TID list,Count,Support
11,"Bread, Butter, Milk","1, 2, 3, 5, 10, 13, 15, 16, 17, 19, 20",11,0.5
15,"Bread, Milk, Wine","1, 2, 5, 10, 13, 14, 15, 16, 19, 20, 21",11,0.5

In [100]:
F4 = []
for i in range(df1.shape[0]):
    for j in range(i + 1, df1.shape[0]):
        for k in range(j + 1, df1.shape[0]):
            for l in range(k + 1, df1.shape[0]):
                # .split(', ') để tách thành list, sau đó set() để chuyển thành tập hợp
                set_i = set(df1.iloc[i]['TID list'].split(', '))
                set_j = set(df1.iloc[j]['TID list'].split(', '))
                set_k = set(df1.iloc[k]['TID list'].split(', '))
                set_l = set(df1.iloc[l]['TID list'].split(', '))
                
                # TÌM GIAO NHAU (Các TID xuất hiện ở cả 3 hàng)
                common_tids = set_i.intersection(set_j, set_k, set_l)
                
                # ĐỊNH DẠNG LẠI KẾT QUẢ
                if common_tids:
                    tid_str = ', '.join(sorted(list(common_tids), key=int))
                else:
                    tid_str = '-'

                F4.append([df1.iloc[i, 0] + ", " + df1.iloc[j, 0] + ", " + df1.iloc[k , 0] + ", " + df1.iloc[l , 0], 
                        tid_str])

df4 = pd.DataFrame(F4, columns=['Items', 'TID list'])
df4

                          Items                         TID list
0   Apple, Bread, Butter, Chips          1, 5, 7, 11, 16, 17, 19
1    Apple, Bread, Butter, Milk         1, 5, 15, 16, 17, 19, 20
2    Apple, Bread, Butter, Wine          1, 5, 7, 15, 16, 19, 20
3     Apple, Bread, Chips, Milk             1, 5, 16, 17, 19, 21
4     Apple, Bread, Chips, Wine              1, 5, 7, 16, 19, 21
5      Apple, Bread, Milk, Wine     1, 5, 14, 15, 16, 19, 20, 21
6    Apple, Butter, Chips, Milk             1, 5, 16, 17, 18, 19
7    Apple, Butter, Chips, Wine                  1, 5, 7, 16, 19
8     Apple, Butter, Milk, Wine         1, 5, 12, 15, 16, 19, 20
9      Apple, Chips, Milk, Wine                 1, 5, 16, 19, 21
10   Bread, Butter, Chips, Milk             1, 5, 13, 16, 17, 19
11   Bread, Butter, Chips, Wine              1, 5, 7, 13, 16, 19
12    Bread, Butter, Milk, Wine  1, 2, 5, 10, 13, 15, 16, 19, 20
13     Bread, Chips, Milk, Wine             1, 5, 13, 16, 19, 21
14    Butter, Chips, Milk, Wine                 1, 5, 13, 16, 19

In [101]:
df4['Count'] = df4['TID list'].str.count(',') + 1
df4['Support'] = df4['Count'] / 22

df4 = df4[df4['Count'] >= min_combination]
df4 = df4[df4['Support'] >= min_support]
df4

Empty DataFrame
Columns: [Items, TID list, Count, Support]
Index: []

In [96]:
results = pd.concat([df2, df3])
results

,Items,TID list,Count,Support
0,"Apple, Bread","1, 5, 7, 9, 11, 14, 15, 16, 17, 19, 20, 21",12,0.545455
1,"Apple, Butter","1, 5, 7, 11, 12, 15, 16, 17, 18, 19, 20",11,0.500000
3,"Apple, Milk","1, 5, 12, 14, 15, 16, 17, 18, 19, 20, 21",11,0.500000
4,"Apple, Wine","1, 5, 7, 9, 12, 14, 15, 16, 19, 20, 21",11,0.500000
5,"Bread, Butter","1, 2, 3, 5, 7, 10, 11, 13, 15, 16, 17, 19, 20",13,0.590909
7,"Bread, Milk","1, 2, 3, 5, 10, 13, 14, 15, 16, 17, 19, 20, 21",13,0.590909
8,"Bread, Wine","1, 2, 5, 7, 9, 10, 13, 14, 15, 16, 19, 20, 21",13,0.590909
10,"Butter, Milk","1, 2, 3, 5, 10, 12, 13, 15, 16, 17, 18, 19, 20",13,0.590909
11,"Butter, Wine","1, 2, 5, 7, 10, 12, 13, 15, 16, 19, 20",11,0.500000
14,"Milk, Wine","1, 2, 5, 6, 8, 10, 12, 13, 14, 15, 16, 19, 20, 21",14,0.636364
11,"Bread, Butter, Milk","1, 2, 3, 5, 10, 13, 15, 16, 17, 19, 20",11,0.500000
15,"Bread, Milk, Wine","1, 2, 5, 10, 13, 14, 15, 16, 19, 20, 21",11,0.500000